### ISSUE TITLE
Issues in R with Tidy Synth

### ISSUE THREAD

**Issue by UA2105** [edunford/tidysynth#10]
Hi ,
I am trying to use Tidy synth to do some work and i keep getting errors and i am unable to get the final results. I am attaching my code . Any help would be much appreciated
![image](https://user-images.githubusercontent.com/94126100/141322820-a5a95f27-b342-4f5f-9746-df7818bb70bc.png)

**Comment by UA2105** [comment]
![image](https://user-images.githubusercontent.com/94126100/141323099-892e77e1-8a16-4e64-b929-bf05e08a39bc.png)

**Comment by filipemsc** [comment]
Please post your code instead of an image and make your example reproducible for the reader when you're asking. See some tips here: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

Apparently, the problem is that you did not specify the "data" argument in the row 8.
