### ISSUE TITLE
Validation of fit

### ISSUE THREAD

**Issue by LSYS** [edunford/tidysynth#7]
Is splitting of pre-treatment periods into training + validation samples in the pipeline?

**Comment by edunford** [comment]
Could you be more specific on the issue and provide an example? The synthetic control method aims to minimize the error in the pre-treatment period fit so that the observed and synthetic values map as closely as possible. The approach doesn't follow a normal ML workflow (see the Abadie et al. papers cited in the readme ... but mainly the limitation for any splitting procedure has to do with the size of the sample), so not sure what you mean here.
